# .github/workflows/main.yml

name: Playwright Test Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        browser: [chromium]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist behave-html-formatter
        
        # Verify installations
        python --version
        pip --version
        behave --version
        playwright --version

    - name: Install Playwright Browsers
      run: |
        playwright install ${{ matrix.browser }}
        playwright install-deps ${{ matrix.browser }}

    - name: Create directories
      run: |
        mkdir -p logs
        mkdir -p reports
        mkdir -p screenshots

    - name: List Feature Files
      run: |
        echo "Available feature files:"
        ls -R features/*.feature
        
        echo "Available tags:"
        behave --tags-help

    - name: Run Smoke Tests
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev  # Match your local environment
      run: |
        behave --tags="@smoke" -v --format=progress2 --format=json.pretty -o reports/smoke_results.json

    - name: Run P1 Tests
      if: success() || failure()  # Run even if smoke tests fail
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev
      run: |
        behave --tags="@p1" --format=progress2 --format=json.pretty -o reports/p1_results.json

    - name: Run Remaining Tests
      if: success() || failure()  # Run even if previous tests fail
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev
      run: |
        behave --tags="~@smoke and ~@p1" --format=progress2 --format=json.pretty -o reports/other_results.json

    - name: Generate Combined Report
      if: always()
      run: |
        # Install additional reporting tools if needed
        pip install junit2html
        
        # Combine reports
        python .github/scripts/combine_reports.py

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          reports/
          logs/
          screenshots/

    # Upload test results even on failure
    - name: Upload Test Results on Failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-on-failure
        path: |
          reports/
          logs/
          screenshots/