name: Playwright Test Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        browser: [chromium]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist behave-html-formatter

    - name: Install Playwright
      run: |
        playwright install --with-deps ${{ matrix.browser }}
        
    - name: Create directories
      run: |
        mkdir -p logs
        mkdir -p reports
        mkdir -p screenshots

    - name: Run Smoke Tests
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev
        PWTEST_HEADED: "0"  # Force headless mode
        DISPLAY: ":99.0"
      run: |
        # Start virtual display
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
        # Run tests with proper headless configuration
        behave --tags="@smoke" -v --format=progress2 --format=json.pretty -o reports/smoke_results.json
      
    - name: Run P1 Tests
      if: success() || failure()
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev
        PWTEST_HEADED: "0"
        DISPLAY: ":99.0"
      run: |
        behave --tags="@p1" -v --format=progress2 --format=json.pretty -o reports/p1_results.json

    - name: Run Remaining Tests
      if: success() || failure()
      env:
        BROWSER: ${{ matrix.browser }}
        ENVIRONMENT: dev
        PWTEST_HEADED: "0"
        DISPLAY: ":99.0"
      run: |
        behave --tags="~@smoke and ~@p1" -v --format=progress2 --format=json.pretty -o reports/other_results.json

    - name: Generate Combined Report
      if: always()
      run: |
        # Install additional reporting tools
        pip install junit2html
        
        # Create empty result files if they don't exist
        touch reports/smoke_results.json
        touch reports/p1_results.json
        touch reports/other_results.json
        
        # Run report generation
        python .github/scripts/combine_reports.py

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          reports/
          logs/
          screenshots/